<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * creditonlineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class aboutRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function addAbout($about)
    {
        $em = $this->getEntityManager();
        $em->persist($about);
        $em->flush();
    }
    
}
