<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Comments;

/**
 * commentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commentsRepository extends \Doctrine\ORM\EntityRepository
{

    public function addComment($comment)
    {
        $em = $this->getEntityManager();
        $em->persist($comment);
        $em->flush();
    }
    
    public function Commit()
    {
        $em = $this->getEntityManager();
        $em->flush();
    }
}
