<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * creditonlineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class articlesRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function addArticle($articles)
    {
        $em = $this->getEntityManager();
        $em->persist($articles);
    }
    
}
