<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Comments;

/**
 * commentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commentsRepository extends \Doctrine\ORM\EntityRepository
{

    public function addComment($user,$mail,$msg,$rating,$service,$proposition)
    {
        $comment = new Comments();
        $comment->setCompanyId($proposition);
        $comment->setUser($user);
        $comment->setMail($mail);
        $comment->setMsg($msg);
        $comment->setRank($rating);
        $comment->setPublDate(new \DateTime());
        $em = $this->getEntityManager();
        $em->persist($comment);
        $em->flush();
    }
}
